# Generated by Django 6.0.2 on 2026-04-19 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_alter_booking_options_booking_agency_booking_notes_and_more'),
        ('properties', '0002_amenity_alter_property_options_property_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.CharField(blank=True, max_length=255)),
                ('scheduled_date', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_tasks', to='bookings.booking')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_tasks', to='properties.property')),
            ],
            options={
                'verbose_name': 'Cleaning Task',
                'verbose_name_plural': 'Cleaning Tasks',
                'ordering': ['scheduled_date'],
            },
        ),
    ]
