# Generated by Django 6.0.2 on 2026-02-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingpayment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bookingpayment',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='bookingpayment',
            name='notes',
        ),
        migrations.AlterField(
            model_name='bookingpayment',
            name='payment_method',
            field=models.CharField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
    ]
