# Generated by Django 6.0.2 on 2026-04-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_bookingpayment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingpayment',
            options={'ordering': ['-due_date'], 'verbose_name': 'Booking Payment', 'verbose_name_plural': 'Booking Payments'},
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='receipt_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
