# Generated by Django 6.0.2 on 2026-09-21 16:15

import django.db.models.deletion
from django.db import migrations, models


def assign_organization(apps, schema_editor):
    """Los datos previos pertenecían a una única organización: se asignan a ella."""
    Organization = apps.get_model('organizations', 'Organization')
    Model = apps.get_model('team', 'TeamMember')
    first = Organization.objects.order_by('id').first()
    if first is None:
        return
    Model.objects.filter(organization__isnull=True).update(organization=first)


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='organizations.organization'),
        ),
        migrations.RunPython(assign_organization, migrations.RunPython.noop),
    ]
