# Generated by Django 6.0.2 on 2026-09-21 16:15

import django.db.models.deletion
from django.db import migrations, models


def assign_organization(apps, schema_editor):
    """Los datos previos pertenecían a una única organización: se asignan a ella."""
    Organization = apps.get_model('organizations', 'Organization')
    Model = apps.get_model('clients', 'Client')
    first = Organization.objects.order_by('id').first()
    if first is None:
        return
    Booking = apps.get_model('bookings', 'Booking')
    for client in Model.objects.filter(organization__isnull=True):
        booking = Booking.objects.filter(client=client).select_related('apartment').first()
        if booking and booking.apartment.organization_id:
            client.organization_id = booking.apartment.organization_id
            client.save(update_fields=['organization'])
    Model.objects.filter(organization__isnull=True).update(organization=first)


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options_client_nationality_and_more'),
        ('organizations', '0001_initial'),
        ('bookings', '0005_booking_deposit_amount_booking_deposit_returned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='organizations.organization'),
        ),
        migrations.RunPython(assign_organization, migrations.RunPython.noop),
    ]
