# Generated by Django 6.0.2 on 2026-05-02 14:47

import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_amenity_alter_property_options_property_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=properties.models.property_image_path),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
