# Generated by Django 6.0.2 on 2026-05-18 15:51

from django.db import migrations, models


AMENITIES = [
    ('Acceso a Internet', 'wifi', 'INTERNET'),
    ('Wireless Internet', 'wifi', 'INTERNET'),
    ('Aire acondicionado', 'snowflake', 'COMFORT'),
    ('Bomba de calor', 'thermometer', 'COMFORT'),
    ('Placas eléctricas', 'utensils', 'KITCHEN'),
    ('Microondas', 'microwave', 'KITCHEN'),
    ('Nevera', 'refrigerator', 'KITCHEN'),
    ('Congelador', 'snowflake', 'KITCHEN'),
    ('Cafetera', 'coffee', 'KITCHEN'),
    ('Tostador', 'sandwich', 'KITCHEN'),
    ('Cubertería', 'utensils', 'KITCHEN'),
    ('Televisión', 'tv', 'MULTIMEDIA'),
    ('Lavadora', 'washing-machine', 'COMFORT'),
    ('Plancha', 'shirt', 'COMFORT'),
    ('Tabla de planchar', 'shirt', 'COMFORT'),
    ('Ropa blanca incluida', 'bed', 'SERVICES'),
    ('Edredones y mantas', 'bed', 'COMFORT'),
    ('WC independiente', 'bath', 'BATHROOM'),
    ('Bañera', 'bath', 'BATHROOM'),
    ('Ducha', 'shower-head', 'BATHROOM'),
    ('Balcones', 'door-open', 'OUTDOOR'),
    ('Vistas a la Catedral', 'landmark', 'OUTDOOR'),
    ('Parking privado', 'parking-circle', 'BUILDING'),
    ('Ascensor', 'arrow-up-down', 'BUILDING'),
    ('Toallas incluidas', 'bath', 'SERVICES'),
    ('Sábanas incluidas', 'bed', 'SERVICES'),
    ('Posibilidad de limpieza', 'sparkles', 'SERVICES'),
    ('Animales autorizados', 'paw-print', 'RULES'),
]


def seed_amenities(apps, schema_editor):
    Amenity = apps.get_model('properties', 'Amenity')
    for name, icon, category in AMENITIES:
        Amenity.objects.update_or_create(
            name=name,
            defaults={'icon': icon, 'category': category},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_propertyimage_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='category',
            field=models.CharField(choices=[('INTERNET', 'Internet'), ('KITCHEN', 'Kitchen'), ('BATHROOM', 'Bathroom'), ('MULTIMEDIA', 'Multimedia'), ('COMFORT', 'Comfort'), ('OUTDOOR', 'Outdoor'), ('BUILDING', 'Building'), ('SERVICES', 'Services'), ('SAFETY', 'Safety'), ('ACCESSIBILITY', 'Accessibility'), ('RULES', 'Rules'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='amenity',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='beds',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='construction_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='distribution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='property',
            name='equipment',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='property',
            name='floor',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='property',
            name='renovation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='size_m2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='tourist_registration_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(seed_amenities, migrations.RunPython.noop),
    ]
