# Generated by Django 6.0.2 on 2026-05-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_amenity_category_amenity_description_property_beds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
