# Generated by Django 6.0.2 on 2026-05-02 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='team.teammember'),
        ),
    ]
