# Generated by Django 6.0.2 on 2026-05-18 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0004_booking_client_email_booking_client_name_and_more'),
        ('clients', '0002_alter_client_options_client_nationality_and_more'),
        ('properties', '0003_propertyimage_image_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('event', models.CharField(choices=[('CLIENT_CREATED', 'Client created'), ('BOOKING_CREATED', 'Booking created'), ('MAINTENANCE_CREATED', 'Maintenance created'), ('MAINTENANCE_UPDATED', 'Maintenance updated'), ('CHECKIN_COMPLETED', 'Check-in completed')], max_length=40)),
                ('target', models.CharField(choices=[('N8N', 'n8n'), ('WHATSAPP', 'WhatsApp'), ('TELEGRAM', 'Telegram'), ('CUSTOM', 'Custom')], default='N8N', max_length=30)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('secret', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webhook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='integrations.automationwebhook')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicPricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weekend_markup_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('occupancy_markup_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_minute_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('provider', models.CharField(default='BASIC', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='GuestCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('document_id', models.CharField(blank=True, max_length=80)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('signature_data', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_checkin', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='InboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('AIRBNB', 'Airbnb'), ('BOOKING', 'Booking.com'), ('VRBO', 'Vrbo'), ('EXPEDIA', 'Expedia'), ('TRIPADVISOR', 'Tripadvisor'), ('AGODA', 'Agoda'), ('GOOGLE_VR', 'Google Vacation Rentals'), ('DIRECT', 'Web directa'), ('ICAL', 'iCal'), ('WHATSAPP', 'WhatsApp'), ('TELEGRAM', 'Telegram'), ('EMAIL', 'Email')], max_length=30)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=20)),
                ('sender', models.CharField(blank=True, max_length=255)),
                ('recipient', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='bookings.booking')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('STRIPE', 'Stripe'), ('REDSYS', 'Redsys'), ('MERCADOPAGO', 'MercadoPago'), ('MANUAL', 'Manual')], default='MANUAL', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20)),
                ('checkout_url', models.URLField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_nights', models.PositiveIntegerField(default=1)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_rates', to='properties.property')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='SmartLockCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('NUKI', 'Nuki'), ('YALE', 'Yale'), ('REMOTELOCK', 'RemoteLock'), ('TTLOCK', 'TTLock'), ('MANUAL', 'Manual')], default='MANUAL', max_length=30)),
                ('code', models.CharField(max_length=40)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_lock_codes', to='bookings.booking')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_lock_codes', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('AIRBNB', 'Airbnb'), ('BOOKING', 'Booking.com'), ('VRBO', 'Vrbo'), ('EXPEDIA', 'Expedia'), ('TRIPADVISOR', 'Tripadvisor'), ('AGODA', 'Agoda'), ('GOOGLE_VR', 'Google Vacation Rentals'), ('DIRECT', 'Web directa'), ('ICAL', 'iCal')], max_length=30)),
                ('external_listing_id', models.CharField(blank=True, max_length=255)),
                ('ical_import_url', models.URLField(blank=True)),
                ('ical_export_token', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONNECTED', 'Connected'), ('ERROR', 'Error'), ('PAUSED', 'Paused')], default='DRAFT', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('content_sync_enabled', models.BooleanField(default=True)),
                ('rates_sync_enabled', models.BooleanField(default=True)),
                ('availability_sync_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_connections', to='properties.property')),
            ],
            options={
                'ordering': ['property', 'channel'],
                'unique_together': {('property', 'channel', 'external_listing_id')},
            },
        ),
    ]
