# Generated by Django 6.0.2 on 2026-08-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_client_email_booking_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
