# Generated by Django 6.0.2 on 2026-09-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_void',
            field=models.BooleanField(default=False),
        ),
    ]
