# Generated by Django 6.0.2 on 2026-04-19 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_alter_booking_options_booking_agency_booking_notes_and_more'),
        ('properties', '0002_amenity_alter_property_options_property_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(choices=[('BOOKING', 'Booking'), ('MAINTENANCE', 'Maintenance'), ('CLEANING', 'Cleaning'), ('OWNER_USE', 'Owner Use'), ('BLOCKED', 'Blocked')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_blocks', to='bookings.booking')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_blocks', to='properties.property')),
            ],
            options={
                'verbose_name': 'Calendar Block',
                'verbose_name_plural': 'Calendar Blocks',
                'ordering': ['start_date'],
            },
        ),
    ]
